# Generated by Django 5.2.13 on 2026-05-04 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Ամրագրում', 'verbose_name_plural': 'Ամրագրումներ'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Սենյակ', 'verbose_name_plural': 'Սենյակներ'},
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Սենյակի լուսանկար'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(verbose_name='Մուտքի ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ստեղծման ամսաթիվ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=100, verbose_name='Հյուրի անուն'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nights',
            field=models.PositiveIntegerField(default=1, verbose_name='Գիշերների քանակ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='hotel.room', verbose_name='Սենյակ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ընդհանուր արժեք'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2, verbose_name='Տարողություն'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Հասանելի է'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Գին մեկ գիշերվա համար'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Սենյակի համար'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=50, verbose_name='Սենյակի տեսակ'),
        ),
    ]
